server:
  port: ${APPLICATION_PORT:8085}
---
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://35.222.177.16:3307/db_customer_service?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    hibernate.ddl-auto: none

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: /metrics
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus

logging:
  level:
    org.springframework: ERROR
    com.mkyong: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log